# stg='''Hey There !
# welcome to world '''
# print(stg)

# -------------------
# slicing

# stg="simplilearn"
# print(stg[0:5])
# print(stg[:5])
# print(stg[5:])
# print(stg[2:5])
# ---------------------------------------

# stg="Hi Shashikant"
# print(stg.upper())
# print(stg.lower())
# print(stg.find('k'))
# print(stg.index('k'))
# -----------------------------

# stg="Welcome to simplilearn"
# print(stg.split(" "))
# --------------------------------------------

# stg1="Hey"
# stg2="there"
# stg3="all"
# stg="{} {}, {}!".format(stg1,stg2,stg3)
# print(stg)
# -------------------------------------------
